export const products = [
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
	{
		name: 'Nestle Kitkat Mini, Big Size Caramel Pudding',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
	},
];

export const productsCarouselData = [
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
	{
		name: 'Guava Fruit Fresh',
		price: '220',
		size: '1kg',
		image: '/product-image/guava-fruit-fresh.png',
		ifPlasticFree: true,
	},
];
