export const accordionCategory = {
	id: 2,
	parent_id: 1,
	name: 'Default Category',
	is_active: true,
	position: 1,
	level: 1,
	product_count: 2903,
	children_data: [
		{
			id: 54,
			parent_id: 2,
			name: 'Grocery',
			is_active: true,
			position: 9,
			level: 2,
			product_count: 1344,
			children_data: [
				{
					id: 61,
					parent_id: 54,
					name: 'Fruits & Vegetables ',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 119,
					children_data: [
						{
							id: 102,
							parent_id: 61,
							name: 'Fresh vegetable',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 79,
							children_data: [],
						},
						{
							id: 63,
							parent_id: 61,
							name: 'Fresh Fruits',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 40,
							children_data: [],
						},
					],
				},
				{
					id: 65,
					parent_id: 54,
					name: 'Meat & Fish ',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 60,
					children_data: [
						{
							id: 66,
							parent_id: 65,
							name: 'Chicken & Poultry',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 22,
							children_data: [],
						},
						{
							id: 67,
							parent_id: 65,
							name: 'Fish',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 20,
							children_data: [],
						},
						{
							id: 68,
							parent_id: 65,
							name: 'Meat',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 17,
							children_data: [],
						},
						{
							id: 70,
							parent_id: 65,
							name: 'Dried Fish',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 1,
							children_data: [],
						},
					],
				},
				{
					id: 71,
					parent_id: 54,
					name: 'Cooking ',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 367,
					children_data: [
						{
							id: 74,
							parent_id: 71,
							name: 'Rice',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 71,
							children_data: [],
						},
						{
							id: 79,
							parent_id: 71,
							name: 'Oil',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 54,
							children_data: [],
						},
						{
							id: 75,
							parent_id: 71,
							name: 'Dal or Lentil',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 26,
							children_data: [],
						},
						{
							id: 73,
							parent_id: 71,
							name: 'Salt & Sugar',
							is_active: true,
							position: 4,
							level: 4,
							product_count: 18,
							children_data: [],
						},
						{
							id: 72,
							parent_id: 71,
							name: 'Spices',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 100,
							children_data: [],
						},
						{
							id: 76,
							parent_id: 71,
							name: 'Ready Mix',
							is_active: true,
							position: 6,
							level: 4,
							product_count: 47,
							children_data: [],
						},
						{
							id: 1650,
							parent_id: 71,
							name: 'Ready To Eat',
							is_active: true,
							position: 7,
							level: 4,
							product_count: 6,
							children_data: [],
						},
						{
							id: 77,
							parent_id: 71,
							name: 'Shemai & Suji',
							is_active: true,
							position: 8,
							level: 4,
							product_count: 11,
							children_data: [],
						},
						{
							id: 78,
							parent_id: 71,
							name: 'Special Ingredients',
							is_active: true,
							position: 9,
							level: 4,
							product_count: 21,
							children_data: [],
						},
						{
							id: 80,
							parent_id: 71,
							name: 'Colors & Flavors',
							is_active: true,
							position: 11,
							level: 4,
							product_count: 13,
							children_data: [],
						},
					],
				},
				{
					id: 83,
					parent_id: 54,
					name: 'Sauces & Pickles ',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 84,
					children_data: [
						{
							id: 84,
							parent_id: 83,
							name: 'Tomato Sauces',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 40,
							children_data: [],
						},
						{
							id: 1537,
							parent_id: 83,
							name: 'Cooking Sauces',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 19,
							children_data: [],
						},
						{
							id: 1536,
							parent_id: 83,
							name: 'Pickles',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 22,
							children_data: [],
						},
					],
				},
				{
					id: 85,
					parent_id: 54,
					name: 'Dairy & Eggs ',
					is_active: true,
					position: 5,
					level: 3,
					product_count: 99,
					children_data: [
						{
							id: 86,
							parent_id: 85,
							name: 'Eggs',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 7,
							children_data: [],
						},
						{
							id: 87,
							parent_id: 85,
							name: 'Powder Milk',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 24,
							children_data: [],
						},
						{
							id: 88,
							parent_id: 85,
							name: 'Liquid & UHT Milk',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 18,
							children_data: [],
						},
						{
							id: 89,
							parent_id: 85,
							name: 'Yogurt & Sweets',
							is_active: true,
							position: 6,
							level: 4,
							product_count: 6,
							children_data: [],
						},
						{
							id: 81,
							parent_id: 85,
							name: 'Ghee',
							is_active: true,
							position: 7,
							level: 4,
							product_count: 16,
							children_data: [],
						},
						{
							id: 90,
							parent_id: 85,
							name: 'Cheese',
							is_active: true,
							position: 8,
							level: 4,
							product_count: 22,
							children_data: [],
						},
						{
							id: 92,
							parent_id: 85,
							name: 'Butter & Sour Cream',
							is_active: true,
							position: 10,
							level: 4,
							product_count: 6,
							children_data: [],
						},
					],
				},
				{
					id: 93,
					parent_id: 54,
					name: 'Breakfast ',
					is_active: true,
					position: 6,
					level: 3,
					product_count: 68,
					children_data: [
						{
							id: 1028,
							parent_id: 93,
							name: 'Cereals',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 20,
							children_data: [],
						},
						{
							id: 1395,
							parent_id: 93,
							name: 'Dips',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 17,
							children_data: [],
						},
						{
							id: 1534,
							parent_id: 93,
							name: 'Honey',
							is_active: true,
							position: 7,
							level: 4,
							product_count: 18,
							children_data: [],
						},
						{
							id: 94,
							parent_id: 93,
							name: 'Breads',
							is_active: true,
							position: 9,
							level: 4,
							product_count: 8,
							children_data: [],
						},
					],
				},
				{
					id: 459,
					parent_id: 54,
					name: 'Beverages',
					is_active: true,
					position: 7,
					level: 3,
					product_count: 165,
					children_data: [
						{
							id: 460,
							parent_id: 459,
							name: 'Syrups & Powder Drinks',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 43,
							children_data: [],
						},
						{
							id: 827,
							parent_id: 459,
							name: 'Tea',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 36,
							children_data: [],
						},
						{
							id: 980,
							parent_id: 459,
							name: 'Coffee',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 25,
							children_data: [],
						},
						{
							id: 1402,
							parent_id: 459,
							name: 'Soft Drinks',
							is_active: true,
							position: 4,
							level: 4,
							product_count: 41,
							children_data: [],
						},
						{
							id: 1543,
							parent_id: 459,
							name: 'Water',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 20,
							children_data: [],
						},
					],
				},
				{
					id: 461,
					parent_id: 54,
					name: 'Baking',
					is_active: true,
					position: 8,
					level: 3,
					product_count: 57,
					children_data: [
						{
							id: 462,
							parent_id: 461,
							name: 'Flour',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 30,
							children_data: [],
						},
						{
							id: 1268,
							parent_id: 461,
							name: 'Baking Ingredients',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 27,
							children_data: [],
						},
					],
				},
				{
					id: 493,
					parent_id: 54,
					name: 'Snacks',
					is_active: true,
					position: 9,
					level: 3,
					product_count: 164,
					children_data: [
						{
							id: 494,
							parent_id: 493,
							name: 'Popcorn & Nuts',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 20,
							children_data: [],
						},
						{
							id: 520,
							parent_id: 493,
							name: 'Noodles',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 33,
							children_data: [],
						},
						{
							id: 834,
							parent_id: 493,
							name: 'Local Snacks',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 35,
							children_data: [],
						},
						{
							id: 943,
							parent_id: 493,
							name: 'Chips & Pretzels',
							is_active: true,
							position: 4,
							level: 4,
							product_count: 8,
							children_data: [],
						},
						{
							id: 987,
							parent_id: 493,
							name: 'Cream Biscuits',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 14,
							children_data: [],
						},
						{
							id: 988,
							parent_id: 493,
							name: 'Plain Biscuits',
							is_active: true,
							position: 6,
							level: 4,
							product_count: 24,
							children_data: [],
						},
						{
							id: 989,
							parent_id: 493,
							name: 'Toast & Bakery Biscuits',
							is_active: true,
							position: 7,
							level: 4,
							product_count: 3,
							children_data: [],
						},
						{
							id: 990,
							parent_id: 493,
							name: 'Cookies',
							is_active: true,
							position: 8,
							level: 4,
							product_count: 14,
							children_data: [],
						},
						{
							id: 1505,
							parent_id: 493,
							name: 'Cakes',
							is_active: true,
							position: 9,
							level: 4,
							product_count: 2,
							children_data: [],
						},
						{
							id: 1596,
							parent_id: 493,
							name: 'Salted Biscuits',
							is_active: true,
							position: 10,
							level: 4,
							product_count: 2,
							children_data: [],
						},
						{
							id: 1597,
							parent_id: 493,
							name: 'Pasta & Macaroni',
							is_active: true,
							position: 11,
							level: 4,
							product_count: 5,
							children_data: [],
						},
					],
				},
				{
					id: 832,
					parent_id: 54,
					name: 'Frozen & Canned',
					is_active: true,
					position: 10,
					level: 3,
					product_count: 138,
					children_data: [
						{
							id: 833,
							parent_id: 832,
							name: 'Fish Snacks',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 10,
							children_data: [],
						},
						{
							id: 1030,
							parent_id: 832,
							name: 'Vegetable Snacks',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 24,
							children_data: [],
						},
						{
							id: 1031,
							parent_id: 832,
							name: 'Chicken Snacks',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 46,
							children_data: [],
						},
						{
							id: 1226,
							parent_id: 832,
							name: 'Frozen Parathas & Roti',
							is_active: true,
							position: 4,
							level: 4,
							product_count: 32,
							children_data: [],
						},
						{
							id: 1521,
							parent_id: 832,
							name: 'Canned Food',
							is_active: true,
							position: 6,
							level: 4,
							product_count: 17,
							children_data: [],
						},
					],
				},
				{
					id: 1022,
					parent_id: 54,
					name: 'Candy & Chocolate',
					is_active: true,
					position: 11,
					level: 3,
					product_count: 28,
					children_data: [],
				},
				{
					id: 1380,
					parent_id: 54,
					name: 'Diabetic Food',
					is_active: true,
					position: 12,
					level: 3,
					product_count: 3,
					children_data: [],
				},
			],
		},
		{
			id: 56,
			parent_id: 2,
			name: 'Personal Care ',
			is_active: true,
			position: 10,
			level: 2,
			product_count: 904,
			children_data: [
				{
					id: 415,
					parent_id: 56,
					name: "Men's Care",
					is_active: true,
					position: 1,
					level: 3,
					product_count: 172,
					children_data: [
						{
							id: 416,
							parent_id: 415,
							name: "Men's Perfume",
							is_active: true,
							position: 1,
							level: 4,
							product_count: 48,
							children_data: [],
						},
						{
							id: 417,
							parent_id: 415,
							name: "Men's Deodorants",
							is_active: true,
							position: 2,
							level: 4,
							product_count: 8,
							children_data: [],
						},
						{
							id: 422,
							parent_id: 415,
							name: "Men's Shampoos & Conditioners",
							is_active: true,
							position: 3,
							level: 4,
							product_count: 31,
							children_data: [],
						},
						{
							id: 480,
							parent_id: 415,
							name: "Men's Shower Gel",
							is_active: true,
							position: 4,
							level: 4,
							product_count: 7,
							children_data: [],
						},
						{
							id: 711,
							parent_id: 415,
							name: 'Shaving Needs',
							is_active: true,
							position: 7,
							level: 4,
							product_count: 38,
							children_data: [],
						},
						{
							id: 760,
							parent_id: 415,
							name: "Men's Hair Care",
							is_active: true,
							position: 8,
							level: 4,
							product_count: 6,
							children_data: [],
						},
					],
				},
				{
					id: 419,
					parent_id: 56,
					name: "Women's Care",
					is_active: true,
					position: 2,
					level: 3,
					product_count: 265,
					children_data: [
						{
							id: 420,
							parent_id: 419,
							name: "Women's Shampoos & Conditioners",
							is_active: true,
							position: 1,
							level: 4,
							product_count: 112,
							children_data: [],
						},
						{
							id: 425,
							parent_id: 419,
							name: "Women's Shower Gel",
							is_active: true,
							position: 2,
							level: 4,
							product_count: 16,
							children_data: [],
						},
						{
							id: 426,
							parent_id: 419,
							name: 'Face Wash & Scrub',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 46,
							children_data: [],
						},
						{
							id: 484,
							parent_id: 419,
							name: "Women's Soaps",
							is_active: true,
							position: 4,
							level: 4,
							product_count: 26,
							children_data: [],
						},
						{
							id: 712,
							parent_id: 419,
							name: 'Feminine Care',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 34,
							children_data: [],
						},
						{
							id: 713,
							parent_id: 419,
							name: "Women's Perfume",
							is_active: true,
							position: 6,
							level: 4,
							product_count: 17,
							children_data: [],
						},
					],
				},
				{
					id: 423,
					parent_id: 56,
					name: 'Skin Care',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 320,
					children_data: [
						{
							id: 424,
							parent_id: 423,
							name: 'Body & Hair Oil',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 35,
							children_data: [],
						},
						{
							id: 427,
							parent_id: 423,
							name: 'Lotions',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 56,
							children_data: [],
						},
						{
							id: 429,
							parent_id: 423,
							name: 'Face Wash & Mask',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 55,
							children_data: [],
						},
						{
							id: 482,
							parent_id: 423,
							name: 'Soap',
							is_active: true,
							position: 4,
							level: 4,
							product_count: 76,
							children_data: [],
						},
						{
							id: 491,
							parent_id: 423,
							name: 'Petroleum Jelly',
							is_active: true,
							position: 5,
							level: 4,
							product_count: 13,
							children_data: [],
						},
						{
							id: 492,
							parent_id: 423,
							name: 'Creams',
							is_active: true,
							position: 6,
							level: 4,
							product_count: 68,
							children_data: [],
						},
						{
							id: 483,
							parent_id: 423,
							name: 'Personal Care ',
							is_active: false,
							position: 7,
							level: 4,
							product_count: 0,
							children_data: [],
						},
						{
							id: 490,
							parent_id: 423,
							name: 'Talcom Powder',
							is_active: true,
							position: 8,
							level: 4,
							product_count: 14,
							children_data: [],
						},
					],
				},
				{
					id: 702,
					parent_id: 56,
					name: 'Handwash',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 92,
					children_data: [
						{
							id: 703,
							parent_id: 702,
							name: 'Liquid Handwash',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 72,
							children_data: [],
						},
						{
							id: 707,
							parent_id: 702,
							name: 'Hand Sanitizer',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 18,
							children_data: [],
						},
					],
				},
				{
					id: 714,
					parent_id: 56,
					name: 'Oral Care',
					is_active: true,
					position: 6,
					level: 3,
					product_count: 93,
					children_data: [
						{
							id: 715,
							parent_id: 714,
							name: 'Toothbrushes',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 21,
							children_data: [],
						},
						{
							id: 716,
							parent_id: 714,
							name: 'Toothpastes',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 60,
							children_data: [],
						},
						{
							id: 944,
							parent_id: 714,
							name: 'Mouthwash & Others',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 12,
							children_data: [],
						},
					],
				},
				{
					id: 831,
					parent_id: 56,
					name: 'Hair Color',
					is_active: true,
					position: 7,
					level: 3,
					product_count: 6,
					children_data: [],
				},
				{
					id: 1239,
					parent_id: 56,
					name: 'Tissue & Wipes',
					is_active: true,
					position: 8,
					level: 3,
					product_count: 14,
					children_data: [],
				},
			],
		},
		{
			id: 58,
			parent_id: 2,
			name: 'Baby Care ',
			is_active: true,
			position: 11,
			level: 2,
			product_count: 176,
			children_data: [
				{
					id: 467,
					parent_id: 58,
					name: 'Diapers',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 65,
					children_data: [],
				},
				{
					id: 471,
					parent_id: 58,
					name: 'Wipes',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 17,
					children_data: [],
				},
				{
					id: 1016,
					parent_id: 58,
					name: 'Baby Food',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 26,
					children_data: [],
				},
				{
					id: 1096,
					parent_id: 58,
					name: 'Newborn Essentials',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 10,
					children_data: [],
				},
				{
					id: 1097,
					parent_id: 58,
					name: 'Baby Skincare',
					is_active: true,
					position: 5,
					level: 3,
					product_count: 44,
					children_data: [],
				},
				{
					id: 1098,
					parent_id: 58,
					name: 'Baby Oral Care',
					is_active: true,
					position: 6,
					level: 3,
					product_count: 14,
					children_data: [],
				},
			],
		},
		{
			id: 55,
			parent_id: 2,
			name: 'Cleaning Supplies ',
			is_active: true,
			position: 13,
			level: 2,
			product_count: 245,
			children_data: [
				{
					id: 380,
					parent_id: 55,
					name: 'Dishwashing Supplies',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 29,
					children_data: [],
				},
				{
					id: 101,
					parent_id: 55,
					name: 'Detergents & Dishwashers',
					is_active: false,
					position: 2,
					level: 3,
					product_count: 52,
					children_data: [],
				},
				{
					id: 381,
					parent_id: 55,
					name: 'Laundry',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 35,
					children_data: [],
				},
				{
					id: 418,
					parent_id: 55,
					name: 'Pest Control',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 48,
					children_data: [],
				},
				{
					id: 742,
					parent_id: 55,
					name: 'Floor & Glass Cleaners',
					is_active: true,
					position: 5,
					level: 3,
					product_count: 44,
					children_data: [],
				},
				{
					id: 753,
					parent_id: 55,
					name: 'Air Fresheners',
					is_active: true,
					position: 6,
					level: 3,
					product_count: 31,
					children_data: [],
				},
				{
					id: 828,
					parent_id: 55,
					name: 'Cleaning Accessories',
					is_active: true,
					position: 7,
					level: 3,
					product_count: 14,
					children_data: [],
				},
				{
					id: 1427,
					parent_id: 55,
					name: 'Napkins & Paper Products',
					is_active: true,
					position: 8,
					level: 3,
					product_count: 4,
					children_data: [],
				},
			],
		},
		{
			id: 57,
			parent_id: 2,
			name: 'Health & Wellness',
			is_active: true,
			position: 14,
			level: 2,
			product_count: 47,
			children_data: [
				{
					id: 428,
					parent_id: 57,
					name: 'Family Planning',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 18,
					children_data: [],
				},
				{
					id: 545,
					parent_id: 57,
					name: 'Antiseptics',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 23,
					children_data: [],
				},
				{
					id: 1553,
					parent_id: 57,
					name: 'Adult Diapers',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 2,
					children_data: [],
				},
			],
		},
		{
			id: 60,
			parent_id: 2,
			name: 'Pet Care ',
			is_active: true,
			position: 15,
			level: 2,
			product_count: 85,
			children_data: [
				{
					id: 1651,
					parent_id: 60,
					name: 'Cat Food',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 46,
					children_data: [],
				},
				{
					id: 1652,
					parent_id: 60,
					name: 'Dog Food',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 17,
					children_data: [],
				},
				{
					id: 1653,
					parent_id: 60,
					name: 'Bird Food',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 12,
					children_data: [],
				},
				{
					id: 1654,
					parent_id: 60,
					name: 'Aquarium Fish Food',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 10,
					children_data: [],
				},
			],
		},
		{
			id: 506,
			parent_id: 2,
			name: 'Home & Kitchen',
			is_active: true,
			position: 18,
			level: 2,
			product_count: 37,
			children_data: [
				{
					id: 509,
					parent_id: 506,
					name: 'Kitchen Accessories',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 28,
					children_data: [],
				},
				{
					id: 1535,
					parent_id: 506,
					name: 'Disposables',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 7,
					children_data: [],
				},
			],
		},
		{
			id: 754,
			parent_id: 2,
			name: 'Toys & Sports',
			is_active: true,
			position: 19,
			level: 2,
			product_count: 18,
			children_data: [
				{
					id: 755,
					parent_id: 754,
					name: 'Exercise & Fitness',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 2,
					children_data: [],
				},
			],
		},
		{
			id: 1250,
			parent_id: 2,
			name: 'Stationery & Office',
			is_active: true,
			position: 20,
			level: 2,
			product_count: 49,
			children_data: [
				{
					id: 1251,
					parent_id: 1250,
					name: 'Writing & Printing',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 18,
					children_data: [
						{
							id: 1252,
							parent_id: 1251,
							name: 'Pencils',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 5,
							children_data: [],
						},
						{
							id: 1257,
							parent_id: 1251,
							name: 'Highlighters & Markers',
							is_active: true,
							position: 2,
							level: 4,
							product_count: 4,
							children_data: [],
						},
						{
							id: 1381,
							parent_id: 1251,
							name: 'Pens',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 3,
							children_data: [],
						},
					],
				},
				{
					id: 1253,
					parent_id: 1250,
					name: 'Arts & Crafts',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 3,
					children_data: [
						{
							id: 1254,
							parent_id: 1253,
							name: 'Color Pencils',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 3,
							children_data: [],
						},
					],
				},
				{
					id: 1255,
					parent_id: 1250,
					name: 'Organizers',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 17,
					children_data: [
						{
							id: 1256,
							parent_id: 1255,
							name: 'Measuring Tools',
							is_active: true,
							position: 1,
							level: 4,
							product_count: 4,
							children_data: [],
						},
						{
							id: 1262,
							parent_id: 1255,
							name: 'Tapes',
							is_active: false,
							position: 2,
							level: 4,
							product_count: 0,
							children_data: [],
						},
						{
							id: 1542,
							parent_id: 1255,
							name: 'Cutting',
							is_active: true,
							position: 3,
							level: 4,
							product_count: 1,
							children_data: [],
						},
					],
				},
				{
					id: 1378,
					parent_id: 1250,
					name: 'Office Essential',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 15,
					children_data: [],
				},
				{
					id: 1382,
					parent_id: 1250,
					name: 'Paper',
					is_active: true,
					position: 5,
					level: 3,
					product_count: 4,
					children_data: [],
				},
			],
		},
		{
			id: 1245,
			parent_id: 2,
			name: 'Vehicle Essentials',
			is_active: true,
			position: 21,
			level: 2,
			product_count: 18,
			children_data: [],
		},
		{
			id: 1646,
			parent_id: 2,
			name: 'BOGO',
			is_active: true,
			position: 22,
			level: 2,
			product_count: 31,
			children_data: [],
		},
		{
			id: 1648,
			parent_id: 2,
			name: 'Offer',
			is_active: true,
			position: 24,
			level: 2,
			product_count: 81,
			children_data: [],
		},
		{
			id: 1649,
			parent_id: 2,
			name: 'Plastic free',
			is_active: true,
			position: 25,
			level: 2,
			product_count: 74,
			children_data: [],
		},
		{
			id: 1655,
			parent_id: 2,
			name: 'Promotion',
			is_active: true,
			position: 26,
			level: 2,
			product_count: 16,
			children_data: [
				{
					id: 1656,
					parent_id: 1655,
					name: '1',
					is_active: true,
					position: 1,
					level: 3,
					product_count: 0,
					children_data: [],
				},
				{
					id: 1659,
					parent_id: 1655,
					name: '2',
					is_active: true,
					position: 2,
					level: 3,
					product_count: 2,
					children_data: [],
				},
				{
					id: 1660,
					parent_id: 1655,
					name: 'Broiler Chicken Breast Boneless',
					is_active: true,
					position: 3,
					level: 3,
					product_count: 2,
					children_data: [],
				},
				{
					id: 1662,
					parent_id: 1655,
					name: 'Bruvana Sports Electrolyte Beverages',
					is_active: true,
					position: 4,
					level: 3,
					product_count: 2,
					children_data: [],
				},
				{
					id: 1664,
					parent_id: 1655,
					name: 'Loose Rice',
					is_active: true,
					position: 5,
					level: 3,
					product_count: 3,
					children_data: [],
				},
				{
					id: 1665,
					parent_id: 1655,
					name: 'Chicken',
					is_active: true,
					position: 6,
					level: 3,
					product_count: 9,
					children_data: [],
				},
				{
					id: 1666,
					parent_id: 1655,
					name: 'Aarong Natural Miniket and Nazirshail Rice',
					is_active: true,
					position: 7,
					level: 3,
					product_count: 2,
					children_data: [],
				},
			],
		},
	],
};
